### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#69]
i have error in magento 2.4.0
Elasticsearch: No alive nodes found in your cluster
i use these settings:
![Screenshot_1](https://user-images.githubusercontent.com/17824457/90525050-7a73f900-e177-11ea-9963-0929358e4c4c.png)

**Comment by srgrbkl** [comment]
service elasticsearch start - helped me, but it is inconvenient to enter this command every time when 'vagrant up'

**Comment by srgrbkl** [comment]
I think need to add these commands to shell file:
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service

**Comment by zepgram** [comment]
Can you tell me what is the value of "JAVA_HOME" in your /etc/default/elasticsearch ?

On elasticsearch7 it must be:
"JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre"

I had this issue but it should be solved here:
https://github.com/zepgram/magento2-fast-vm/blob/master/provision/020-system-services.sh#L212

**Comment by srgrbkl** [comment]
correct, i have  same value by default:
"JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre"
but i still get notification

**Comment by zepgram** [comment]
This command is supposed to be run 1 time, then at every start up the service is started, according to elasticsearch doc https://www.elastic.co/guide/en/elasticsearch/reference/7.x/deb.html#deb-running-systemd:
```
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
```
And it's done here: 
https://github.com/zepgram/magento2-fast-vm/blob/master/provision/020-system-services.sh#L214

**Comment by srgrbkl** [comment]
you're right, but after research, I noticed that elasticsearch spontaneously turns off

**Comment by zepgram** [comment]
I found out a way to do this here: https://github.com/elastic/ansible-elasticsearch/issues/371 

Could you run this and confirm this is working ? I'll create a new tag if it works.

```
mkdir /etc/systemd/system/elasticsearch.service.d
cat <<'EOF' > /etc/systemd/system/elasticsearch.service.d/override.conf
[Service]
Restart=always
EOF
/bin/systemctl daemon-reload
/bin/systemctl enable elasticsearch.service
/bin/systemctl start elasticsearch.service
```
